Milestone 2: Interactive list
alvarorf/todoit-js pull request #3
Opened 2021-12-02 20:12 UTC by alvarorf

In this milestone, the following features are added:
- A new JavaScript file (completed.js), which contains the 'check' method to update the task's status (completed: true / false) is added and imported as a module.
- Each checkbox has an event listener which will triger the 'check' method.
- Uses an object-oriented approach.
- Stores the updated array of items in local storage, so the user gets the correct list values after the page reloads.

Note: Some functions for the next milestone are sketched, but are non-functional.

2021-12-02 20:25 UTC, BrianSammit requested changes
# CHANGES REQUIRED 🔴 🛑
Hello @alvarorf, great job you are doing so far in this project. 💯
TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 
- Great job Implementing the updated status
  
However, there are a few changes to make to move to the next project 🛠️ . Keep working hard 💪 💻 

## Required Changes ♻️
See my inline comment to know what changes are needed. 👇 👀 

Please make these required changes and send it again for another review 👍 💪
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
# HAPPY CODING!!! 😄 

![tenor-1](https://user-images.githubusercontent.com/64173189/144497565-fe79f0ab-d02e-4fa9-a529-8c700ca56a9b.gif)


**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-02 20:25 UTC, BrianSammit commented on src/completed.js
> +};
- [ ] It would be better if the status of the tasks persist after reloading the page. Currently, the task changes properly their status but doesn't persist in local storage. Kindly fix this minor issue. 
😄 👍

2021-12-02 22:49 UTC, GzimAsani requested changes
# Hi @alvarorf                              
Good job so far! Your code looks fine, good job :+1:  :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight:
- Great job with the project it looks really good :muscle: 

## Required Changes ♻️ 
- [x] _Check inline comments for more information :arrow_double_down:_ 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-02 22:49 UTC, GzimAsani commented on src/completed.js
> +};
- [ ] I am still having this problem as pointed out by the  previous reviewer and also getting some warnings:
![Screenshot from 2021-12-02 23-46-30](https://user-images.githubusercontent.com/62705947/144515399-ac6d6284-ae35-4abe-9a0e-bee23d1e3e2f.png)

2021-12-03 00:26 UTC, ArthurGC approved these changes
# Approved project!  💯 ✅ 🥳 🎈 🎉
Hi  @alvarorf 

Amazing job implementing suggestions from the previous reviewer! 💯 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media1.giphy.com/media/3o7buh8WbaZLupolXi/giphy.gif)

## Aspects to improve ♻️

- [OPTIONAL] It would be better to fix the broken MIT link in your README file.
- [NOTE] Those errors appear because your `webpack.config.js` is in production mode. If you change it to development mode they won't appear.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-03 03:18 UTC, merged